version: '3.8'

services:
  model-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network
