services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.1
    container_name: clickhouse-db
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=secret
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DB=sales_db
    ports:
      - '8123:8123'
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network
volumes:
  clickhouse_data: