services:
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INNER://0.0.0.0:9092,OUTER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INNER:SASL_PLAINTEXT,OUTER:SASL_PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INNER://kafka:9092,OUTER://localhost:9093
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_INTER_BROKER_LISTENER_NAME: INNER
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas.conf
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./settings/kafka.conf:/etc/kafka/jaas.conf
    ports:
      - '9092:9092'
      - '9093:9093'
    depends_on:
      - zookeeper
    networks:
      - app-network
